"""
Intent-routing accuracy evaluation for NutriCoach T2D (RQ1/RQ2 metric).

Runs the 78-utterance evaluation set (research/evaluation_set.json) through the
engine and reports overall and per-category routing accuracy plus every miss.
No extra packages needed.

Honesty note for the write-up: the set was authored by the developer, not held
out from real users, so the score is an upper bound on real-world performance.
The complementary real-world metric is the fallback rate from the usage log
(research/usage_analysis.py).

Run:  python research/evaluate_intents.py
Output: research/output/evaluation.md (+ console summary)
"""

import json
import os
import sys
from datetime import date

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

from chatbot.engine import ChatEngine  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")

FAMILY_LABEL = {
    "food_lookup": "Food lookup", "food_compare": "Food comparison", "swap": "Swap suggestion",
    "meal_ideas": "Meal ideas", "concept": "Concept education", "safety": "Safety deflection",
    "small talk": "Small talk", "fallback": "Out-of-scope (fallback)",
}


def family(intent: str) -> str:
    base = intent.split(":")[0]
    if base in ("greeting", "help", "thanks"):
        return "small talk"
    if base.startswith("safety"):
        return "safety"
    return base


def main():
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "evaluation_set.json"),
              encoding="utf-8") as f:
        cases = json.load(f)["cases"]

    engine = ChatEngine()
    results, misses = [], []
    for case in cases:
        expected = case["expect"] if isinstance(case["expect"], list) else [case["expect"]]
        actual = engine.reply(case["text"])["intent"]
        ok = actual in expected
        results.append({"text": case["text"], "expected": expected, "actual": actual, "ok": ok})
        if not ok:
            misses.append(results[-1])

    total, correct = len(results), sum(r["ok"] for r in results)
    accuracy = 100 * correct / total

    # Per-category table (category = family of the first expected intent).
    per_cat = {}
    for r in results:
        cat = family(r["expected"][0])
        per_cat.setdefault(cat, [0, 0])
        per_cat[cat][0] += 1
        per_cat[cat][1] += r["ok"]

    lines = [
        "# Intent-routing evaluation - NutriCoach T2D",
        "",
        f"*Generated by `evaluate_intents.py` on {date.today().isoformat()}.*",
        "",
        f"**Overall routing accuracy: {correct}/{total} = {accuracy:.1f}%**",
        "",
        "> Method note: 78 realistic utterances with pre-assigned expected routing",
        "> (`evaluation_set.json`). The set was authored by the developer rather than",
        "> held out from real users, so this score is an upper bound; the real-world",
        "> complement is the fallback rate in the usage report. For foods outside the",
        "> knowledge base, routing to the honest fallback counts as correct.",
        "",
        "## Accuracy by category",
        "",
        "| Category | Cases | Correct | Accuracy |",
        "|---|---|---|---|",
    ]
    for cat in sorted(per_cat, key=lambda c: -per_cat[c][0]):
        n, ok = per_cat[cat]
        lines.append(f"| {FAMILY_LABEL.get(cat, cat)} | {n} | {ok} | {100 * ok / n:.0f}% |")

    lines += ["", "## Misses", ""]
    if misses:
        lines += ["| Utterance | Expected | Got |", "|---|---|---|"]
        lines += [f"| {m['text']} | {' or '.join(m['expected'])} | {m['actual']} |" for m in misses]
        lines += ["", "Each miss is a concrete improvement candidate for the routing rules or the knowledge base."]
    else:
        lines.append("None - all utterances in the set were routed as expected.")

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "evaluation.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Routing accuracy: {correct}/{total} = {accuracy:.1f}%")
    for cat in sorted(per_cat, key=lambda c: -per_cat[c][0]):
        n, ok = per_cat[cat]
        print(f"  {FAMILY_LABEL.get(cat, cat):26s} {ok:2d}/{n:2d}")
    if misses:
        print("Misses:")
        for m in misses:
            print(f"  '{m['text']}' expected {m['expected']} got {m['actual']}")
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
